#ifndef SimpleViewUI_H
#define SimpleViewUI_H

#define SIMPLEVIEW_NUM_ACTORS 4

#include <quat.h>
 
#include <vtkSmartPointer.h>
class vtkRenderer;

#include <QMainWindow>
class QTimer;
class QThread;
class QActionGroup;
#include <QString>

class SketchObject;
namespace SketchBio {
class Project;
class InputManager;
}

class ProjectToXML;

class vrpnServer;

class SubprocessRunner;
 
// Forward Qt class declaration (the view)
class Ui_SimpleView;

/*
 * SimpleView is the main GUI class in the SketchBio project.  It also manages
 * the vrpn input to the program.
 */
class SimpleView : public QMainWindow
{
  Q_OBJECT
public:
 
  // Constructor/Destructor
  SimpleView(QString projDir, bool load_example = false, const QString &deviceFile = "devices/razer_hydra.xml");
  virtual ~SimpleView();

  // Simplify an external object based on the root file name.
  void simplifyObjectByName(const QString name);
 
public slots:

  // Throw a dialog box to browse for an OBJ file to load
  void openOBJFile();

  // Throw a dialog box to type in the name of a PDB ID to import
  // and the chains to remove
  // Run an external Chimera script to download and surface the model
  // Put the resulting model in the project directory.
  void importPDBId();
  // Use a file dialog to select a local PDB file to open and import
  // Also gives a dialog for the chains to remove
  // as a model.  Runs an external Chimera script to surface the model
  // and puts the result in the project folder
  void openPDBFile();
  // Use a file dialog to select a local VTK file to open.  The file
  // is assumed to be one of the VTK files generated by a previous SketchBio
  // project and if filenames matching other VTK files that SketchBio would
  // have generated with it are found, they are included in the resulting model.
  // Filenames tested are:
  // X.vtk
  // X_isosurface.vtk
  // X.decimated.5000.vtk
  // X.decimated.2000.vtk
  // X.decimated.1000.vtk
  void openVTKFile();

  // Export an animation to blender
  // currently writes the test file so I can see if it is correct
  void exportBlenderAnimation();
  // Export current state as a Florosim simulation
  void exportFlorosim();

  // Throw a dialog box to browse for an OBJ file to
  // simplify.  Produce multiple simplifications, with smaller
  // fractional polygon counts.
  void simplifyOBJFile();

  // Restarts the internal vrpn server if there is one.
  void restartVRPNServer();

  // Save the current project
  void saveProjectAs();
  void saveProject();

  // Save a grouped object from clipboard, so it can be
  // loaded into any other project
  void saveCopiedObject();

  // Load object that was saved with saveCopiedObject()
  void loadObject();

  // Add new ellipsoid to the project
  void createEllipsoid();

  // Collision modes (for testing)
  void oldCollisionMode();
  void poseModeTry1();
  void binaryCollisionSearch();
  void poseModePCA();

  // Physics settings
  void setWorldSpringsEnabled(bool enabled);
  void setCollisionTestsOn(bool on);

  // Load a project
  void loadProject();

  virtual void closeEvent(QCloseEvent *);
  virtual void slotExit();
  void slot_frameLoop();

  void goToViewTime();

  void createCameraForViewpoint();
  void setCameraToViewpoint();

protected:
 
protected slots:
  void addUndoStateIfSuccess(bool success);
private slots:
  void updateStatusText();
 
private:

  // Methods
  void runSubprocessAndFreezeGUI(SubprocessRunner *runner,
                                 bool needsUndoState = false);

  class GUIStateHelper;

  // Fields
  Ui_SimpleView *ui;
  QTimer *timer;
  QActionGroup *collisionModeGroup;
  vtkSmartPointer<vtkRenderer> renderer;
  SketchBio::Project *project;
  SketchBio::InputManager *inputManager;
  GUIStateHelper *stateHelper;
};


#endif // SimpleViewUI_H
